[package]
name = "btcusd_stablecoin"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.12.2"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
test-runner = "native"